### ISSUE TITLE
Running `temci setup` fails

### ISSUE THREAD

**Issue by raphinesse** [parttimenerd/temci#12]
Running `temci setup` fails with this error message:
>Running 'make' failed: out="g++ -w -std=c++11 -O3 main.cpp -o ld\nMakefile:2: recipe for target 'all' failed\n", err='g++: error: main.cpp: No such file or directory\ng++: fatal error: no input files\ncompilation terminated.\nmake: *** [all] Error 1\n'

**Comment by parttimenerd** [comment]
Please try to execute `make` in a shell in the `temci/scripts/linker` directory.

**Comment by raphinesse** [comment]
Still fails because of missing input. makes sense too, because there is nothing in that directory except the `Makefile`. Might it be that `main.cpp` somehow gets lost during `pip3` installation?

```
$ make
g++ -w -std=c++11 -O3 main.cpp -o ld
g++: error: main.cpp: No such file or directory
g++: fatal error: no input files
compilation terminated.
Makefile:2: recipe for target 'all' failed
make: *** [all] Error 1
```

**Comment by raphinesse** [comment]
FYI: I'm working on the setup issues and should have some PRs ready some time today.

**Comment by parttimenerd** [comment]
The problem was that I forgot including the main.cpp in the pip version.

**Comment by raphinesse** [comment]
Yes, but there are still the other issues, like the installation errors and missing `entry_points` after installation. Like I said, PRs incoming soon.

**Comment by raphinesse** [comment]
OK, using your changes together with #15, this issue is fixed for me. Furthermore, `ld` seems to be created during installation, which means that running `temci setup` as mentioned in the docs is actually not necessary.

**Comment by parttimenerd** [comment]
Side note: I can't reproduce that `ld` is created automatically (in a clean venv).

**Comment by raphinesse** [comment]
Well that's interesting. I tested in a clean venv too. Installing via `pip install .` from the version from #15. I'll try again and double check.

**Comment by raphinesse** [comment]
OK, so I tested again and it does not auto-build anything. Seems I'm seeing ghosts ;)
