### ISSUE TITLE
Can't import cpu

### ISSUE THREAD

**Issue by yunweilu** [parttimenerd/temci#126]
Error with cset tool.  More specific error (cmd = 'cset set -rl'): Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named 'cpuset'

**Comment by parttimenerd** [comment]
Could you please be more specific? How did you install temci and how did you run it?

**Comment by yunweilu** [comment]
Firstly,

time python3-pandas python3-cffi python3-cairo python3-cairocffi python3-matplotlib python3-numpy python3-scipy linux-tools-`uname -r`

Secondly,
pip3 install git+https://github.com/parttimenerd/temci.git

Finally,
pip3 install https://github.com/pallets/click/archive/f537a208591088499b388b06b2aca4efd5445119.zip.

This is my setup.

I can run the --preset none, but I cannot run preset cpu_governor and others that require root.  Once I try that even without cpu_set, it still gives me the information below:
Error with cset tool. More specific error (cmd = 'cset set -rl'): Traceback (most recent call last):
File "String", line 1, in
ImportError: No module named 'cpuset'.

And I tried to install the cset package, I tried these:
"sudo apt-get install cpuset" 
"pip install cpuset py3"
https://github.com/lpechacek/cpuset
But they still don't work

**Comment by yunweilu** [comment]
> Could you please be more specific? How did you install temci and how did you run it?

No problem.

Firstly,

time python3-pandas python3-cffi python3-cairo python3-cairocffi python3-matplotlib python3-numpy python3-scipy linux-tools-uname -r

Secondly,
pip3 install git+https://github.com/parttimenerd/temci.git

Finally,
pip3 install https://github.com/pallets/click/archive/f537a208591088499b388b06b2aca4efd5445119.zip.

This is my setup.

I can run the --preset none, but I cannot run preset cpu_governor and others that require root. Once I try that even without cpu_set, it still gives me the information below:
Error with cset tool. More specific error (cmd = 'cset set -rl'): Traceback (most recent call last):
File "String", line 1, in
ImportError: No module named 'cpuset'.

And I tried to install the cset package, I tried these:
"sudo apt-get install cpuset"
"pip install cpuset py3"
https://github.com/lpechacek/cpuset
But they still don't work

**Comment by parttimenerd** [comment]
Have you tried to install `temci` or more precisely `cpuset-py3` with super user privileges (`sudo pip3 install cpuset-py3`)?

cpuset-py3 is the fork of cpuset that I use for temci.

**Comment by yunweilu** [comment]
> Have you tried to install `temci` or more precisely `cpuset-py3` with super user privileges (`sudo pip3 install cpuset-py3`)?
> 
> cpuset-py3 is the fork of cpuset that I use for temci.



Thanks! That works!
But new errors pop out then :


[11:16:06] Initialize CPUSet
[11:16:06] Move all processes to new root cpuset
[11:16:08] Finished initializing CPUSet
Discarded benchmark 1 out of 1    [------------------------------------]    0%[11:16:08] Program block no. 0 failed: Unexpected return code 127, expected 0
[11:16:08] error

sh: 0: Can't open /tmp/tmpqo0yz82q

[11:16:08] Program block no. 1 failed: Unexpected return code 127, expected 0
[11:16:08] error

sh: 0: Can't open /tmp/tmp8l6qed99

[11:16:08] Program block no. 2 failed: Unexpected return code 127, expected 0
[11:16:08] error

sh: 0: Can't open /tmp/tmpfobzw0vn

Benchmark 1 out of 1              [####################################]  100%
Errorneous runs
	python h_dim500ad.py:
		Unexpected return code 127, expected 0
	python h_dim500ma.py:
		Unexpected return code 127, expected 0
	python h_dim550ad.py:
		Unexpected return code 127, expected 0

**Comment by parttimenerd** [comment]
Are the mentioned temporary files accessible?

**Comment by yunweilu** [comment]
> Are the mentioned temporary files accessible?

No...  it says no such file.

**Comment by parttimenerd** [comment]
I'm pretty sure that the file is generated at https://github.com/parttimenerd/temci/blob/master/temci/run/run_driver.py#L748 (`        cmd_tmp_file = tempfile.NamedTemporaryFile(delete=False)`) to store the command in. Maybe open a python repl and try `ìmport tempfile; tempfile.NamedTemporaryFile(delete=False)`. But I'm out of my wits.

**Comment by yunweilu** [comment]
I try this in the terminal:

>>> import tempfile
>>> tempfile.NamedTemporaryFile(delete=False)
<tempfile._TemporaryFileWrapper object at 0x7f2b643b5700>
>>> tempfile.NamedTemporaryFile(delete=False)
<tempfile._TemporaryFileWrapper object at 0x7f2b64413ee0>
>>> tempfile.NamedTemporaryFile(delete=False)
<tempfile._TemporaryFileWrapper object at 0x7f2b64342910>

Seems like it works well. But how to make sure they exist?

**Comment by yunweilu** [comment]
> I'm pretty sure that the file is generated at https://github.com/parttimenerd/temci/blob/master/temci/run/run_driver.py#L748 (` cmd_tmp_file = tempfile.NamedTemporaryFile(delete=False)`) to store the command in. Maybe open a python repl and try `ìmport tempfile; tempfile.NamedTemporaryFile(delete=False)`. But I'm out of my wits.


I try this in the terminal:

>>> import tempfile
>>> tempfile.NamedTemporaryFile(delete=False)
<tempfile._TemporaryFileWrapper object at 0x7f2b643b5700>
>>> tempfile.NamedTemporaryFile(delete=False)
<tempfile._TemporaryFileWrapper object at 0x7f2b64413ee0>
>>> tempfile.NamedTemporaryFile(delete=False)
<tempfile._TemporaryFileWrapper object at 0x7f2b64342910>

Seems like it works well. But how to make sure they exist?

**Comment by yunweilu** [comment]
> I'm pretty sure that the file is generated at https://github.com/parttimenerd/temci/blob/master/temci/run/run_driver.py#L748 (` cmd_tmp_file = tempfile.NamedTemporaryFile(delete=False)`) to store the command in. Maybe open a python repl and try `ìmport tempfile; tempfile.NamedTemporaryFile(delete=False)`. But I'm out of my wits.


I go through this..
But then, I get this

llf12345@memon:~/Documents/qoc/examples$ temci short exec "python 0_transmon_pi.py" --runs 5 --cpu_governor --sudo
[23:38:37] Error with cset tool.  More specific error (cmd = 'cset set -rl'): Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 't' is not defined

Is this a  bug?
