### ISSUE TITLE
HyperThreading is not re-enabled

### ISSUE THREAD

**Issue by torokati44** [parttimenerd/temci#133]
While `enable_hyper_threading` does get called from `teardown`, it will re-query the HT cores from `/proc/cpuinfo`, which only contains the cores that were not disabled in `disable_hyper_threading`, so no cores are actually brought back online.

**Comment by torokati44** [comment]
It might make sense to instead store exactly which cores were disabled, and when done, use this information to re-enable the same ones

**Comment by parttimenerd** [comment]
You're correct, thanks for your observation.

**Comment by torokati44** [comment]
Thanks for the quick fix!

**Comment by torokati44** [comment]
Is there any chance of a new release being available on PyPI in the near future, with this fixed, and https://github.com/parttimenerd/temci/pull/132 and https://github.com/parttimenerd/temci/pull/131 included?
These are all really important for me to get even basic usability out of the tool, and it'd be a lot more convenient to install a fixed version straight from there instead of from GitHub.

**Comment by parttimenerd** [comment]
I uploaded it, hope it works now.

**Comment by torokati44** [comment]
Yep, works fine, thank you!
