### ISSUE TITLE
Settings file is not applied correctly

### ISSUE THREAD

**Issue by raphinesse** [parttimenerd/temci#14]
A `temci.yaml` file in the working dir gets loaded during execution of temci, but the settings are not applied. Try setting `run/min_runs` and `run/max_runs`. It will still use `20` and `100` respectively

Looking into the code I could verify that the file is actually used to change the defaults of `Settings().type_scheme` and does not actually change the actual values of `Settings().prefs`. I have been able to work around it for now by restoring the (new) defaults after loading the file.

But I couldn't tell how to fix it for good, since there were a couple of things about `Settings` that seemed broken. :confused:

**Comment by parttimenerd** [comment]
Another workaround is to use the command line options.
I didn't use the settings file feature in my bachelor thesis evaluation. Therefore it isn't tested that well.

**Comment by raphinesse** [comment]
So as a follow up: I think the most immediate problem is, that [loading a file sets the defaults](https://github.com/parttimenerd/temci/blob/b9908da/temci/utils/settings.py#L219) when it should actually, IMHO, set the value of the relevant keys.

**Comment by parttimenerd** [comment]
You were totaly correct with your assumption.
Thanks for contributing.

**Comment by raphinesse** [comment]
Thanks for the quick fix. But I still wonder why you are actually changing the default before setting the actual value. Could you elaborate?

**Comment by parttimenerd** [comment]
The order of the two operations isn't critical (they should work on different data structures).

Why I'm modifying the default values in the first place: If I wouldn't the command line options wouldn't work.
