### ISSUE TITLE
Fn dependency does not work on Python 3.10

### ISSUE THREAD

**Issue by eiennohito** [parttimenerd/temci#140]
Also see https://github.com/kachayev/fn.py/issues/91

**Comment by parttimenerd** [comment]
So temci does not work with python 3.10?

**Comment by eiennohito** [comment]
No, the installation fails with an error to install fn.py.

**Comment by parttimenerd** [comment]
I don't think that temci even needs the fn package. Feel free to just remove it and to create a PR.
