### ISSUE TITLE
unsupported operand type(s) for +: 'NoneType' and 'str'

### ISSUE THREAD

**Issue by gimoh** [parttimenerd/temci#16]
Just trying out temci, I started in clean python 3.5.2 installation (in docker container based off [python:3](https://hub.docker.com/_/python/) image), did a `pip install temci` and then:

    # temci short exec --log_level debug -wd 'ls' --runs 10 --no-nice --no-cpuset_active --out out.yaml
    [16:15:21] CPUSet functionality is disabled because root privileges are missing.
    Make the 1 discarded benchmarks   [###---------------------------------]    9%[16:15:21] Program block no. 0 failed: unsupported operand type(s) for +: 'NoneType' and 'str'
    Benchmark 10 times                [####################################]  100%

Any ideas?

Also the log_level seems to have no effect, so can't tell what the problem is.

**Comment by parttimenerd** [comment]
I can't reproduce your error. Could it be that the time utility isn't present in the docker image?
Please try to run `temci setup` and then call your command again.

**Comment by gimoh** [comment]
duh, you're of course right, `/usr/bin/time` wasn't present, `apt install time` fixed it.
Thanks! and sorry for the noise.
