### ISSUE TITLE
Too many digits

### ISSUE THREAD

**Issue by qznc** [parttimenerd/temci#5]
The report shows numbers like "14.28571%" and "100.00000%". It should round in a clever way, so the two examples are shown as "14%" and "100%" instead.

**Comment by qznc** [comment]
Another example is a difference of means per max std dev of 5349.20597%? How about "53σ difference"?

**Comment by parttimenerd** [comment]
My idea for a "clever way" would be to round based on the standard deviation. I.e. if σ is 10% then a mean value of 10.37534 should be displayed as "10" (all other digits a irrelevant).

The way the numbers are displayed is currently straight forward (but can be changed via command line options) and should be improved. Any further suggestions are appreciated.

**Comment by qznc** [comment]
I dug out a Javascript function I wrote elsewhere.
```javascript
function niceNumber(n) {
  for (i = 7; i >= 0; i--) {
    var modfac = Math.pow(10,i);
    if (Math.abs(n) > (8*modfac)) {
      return n - (n % modfac);
    }
  }
  if (n > 1.0)
    return n.toFixed(0);
  return n;
}
```
It is probably not general enough, though.

The magic number "8" can be changed to adapt the effect.

**Comment by qznc** [comment]
Scientific notation can be stupid. Instead of "-3.22e+01", it should be "-32.3".

**Comment by parttimenerd** [comment]
The code that I'm currently developing tries to improve this case by only allowing exponents (the number behind the "e") to be a multiple of k (usually k=3) and omits it if its zero.
