### ISSUE TITLE
`init settings` sets `config` to the file itself

### ISSUE THREAD

**Issue by Kha** [parttimenerd/temci#61]
which is not a good idea

**Comment by parttimenerd** [comment]
I cannot reproduce it. Please give more context.

**Comment by Kha** [comment]
```
$ rm temci.yaml
$ temci init config; grep config temci.yaml
config: ''
$ temci init config; grep config temci.yaml
config: temci.yaml
```
Interestingly, this does not seem to lead to infinite recursion anymore, but it may still not be expected.

**Comment by parttimenerd** [comment]
The reason for this is that the second call to `temci init config` is run in the context of having a pre-existing settings file that temci then uses.

**Comment by Kha** [comment]
So does that mean that `config:` should never be used in a config file? The description suggests that this field can be used to chain config files, but apparently it can't. This is highly confusing.
